SET IDENTITY_INSERT dbo.Suppliers ON

INSERT INTO dbo.Suppliers (Id, Name) VALUES
(1, 'Fresh Farms Produce'),
(2, 'Ocean Catch Fish Market'),
(3, 'Bakery Supplies Co.'),
(4, 'Meat Masters'),
(5, 'Dairy Delight'),
(6, 'Spice World'),
(7, 'Gourmet Goods'),
(8, 'Vegetable Valley'),
(9, 'Coffee and Tea Suppliers'),
(10, 'Pasta Central'),
(11, 'Fruit Fiesta'),
(12, 'Bakery Best'),
(13, 'Condiment Corner'),
(14, 'Seafood Sensations'),
(15, 'Poultry Plus'),
(16, 'Seasonal Suppliers'),
(17, 'Beverage Brothers'),
(18, 'Gourmet Greens'),
(19, 'Sweet Treats Supply'),
(20, 'Frozen Foods Inc.'),
(21, 'Organic Oasis'),
(22, 'Gourmet Grocers'),
(23, 'Fine Food Suppliers');